return {}

-- local function fuzzy()
--   require("sg.extensions.telescope").fuzzy_search_results()
-- end
--
-- return {
--   {
--     "sourcegraph/sg.nvim",
--     dependencies = {
--       -- "nvim-lua/plenary.nvim",
--       "nvim-telescope/telescope.nvim",
--     },
--     keys = {
--       { "<space>se", fuzzy, desc = "SourceGraph" },
--     },
--
--     -- If you have a recent version of lazy.nvim, you don't need to add this!
--     -- build = "nvim -l build/init.lua",
--   },
-- }
