.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PWD_IS_HOME" "1" "March 2016" "" "pwd_is_home"
.
.SH "NAME"
\fBpwd_is_home\fR \- Test if cwd equals or is a sub directory of HOME
.
.SH "SYNOPSIS"
pwd_is_home
.
.br
.
.SH "USAGE"
.
.nf

if pwd_is_home
    printf "$PWD is $HOME\en"
end
.
.fi

