.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PWD_INFO" "1" "March 2016" "" "pwd_info"
.
.SH "NAME"
\fBpwd_info\fR \- Print info about the current working directory
.
.SH "SYNOPSIS"
pwd_info [separator]
.
.br
.
.SH "USAGE"
Inside a regular directory\.
.
.IP "" 4
.
.nf

cd path/to/my/dir
pwd_info /
dir
p/t/my
↵
.
.fi
.
.IP "" 0
.
.P
Inside a git repository\.
.
.IP "" 4
.
.nf

cd path/to/git/repo/sub/dir
pwd_info " "
repo
p t g
sub dir
.
.fi
.
.IP "" 0

