-- This file is generated by ex-colors. The credit goes to the authors and contributors of the original colorscheme alduin.
vim.api.nvim_set_var("colors_name", "ex-alduin")
vim.api.nvim_set_var("terminal_color_0", "#1b1d2b")
vim.api.nvim_set_var("terminal_color_1", "#ff757f")
vim.api.nvim_set_var("terminal_color_2", "#c3e88d")
vim.api.nvim_set_var("terminal_color_3", "#ffc777")
vim.api.nvim_set_var("terminal_color_4", "#82aaff")
vim.api.nvim_set_var("terminal_color_5", "#c099ff")
vim.api.nvim_set_var("terminal_color_6", "#86e1fc")
vim.api.nvim_set_var("terminal_color_7", "#828bb8")
vim.api.nvim_set_var("terminal_color_8", "#444a73")
vim.api.nvim_set_var("terminal_color_9", "#ff8d94")
vim.api.nvim_set_var("terminal_color_10", "#c7fb6d")
vim.api.nvim_set_var("terminal_color_11", "#ffd8ab")
vim.api.nvim_set_var("terminal_color_12", "#9ab8ff")
vim.api.nvim_set_var("terminal_color_13", "#caabff")
vim.api.nvim_set_var("terminal_color_14", "#b2ebff")
vim.api.nvim_set_var("terminal_color_15", "#c8d3f5")
vim.api.nvim_set_hl(0, "Boolean", { link = "Dark_Orange" })
vim.api.nvim_set_hl(0, "Character", { link = "Dark_Orange" })
vim.api.nvim_set_hl(0, "ColorColumn", { bg = 1122867, ctermbg = 233, fg = 16777215 })
vim.api.nvim_set_hl(0, "Comment", { fg = 10198692, link = "Green" })
vim.api.nvim_set_hl(0, "Conceal", { bg = 0, fg = 1118481 })
vim.api.nvim_set_hl(0, "Conditional", { link = "Grey" })
vim.api.nvim_set_hl(0, "Constant", { fg = 14738154, link = "Soft_Red" })
vim.api.nvim_set_hl(0, "Cursor", { bg = 14671791, ctermbg = 187, ctermfg = 16, fg = 0 })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = 0, ctermbg = 16 })
vim.api.nvim_set_hl(0, "CursorLine", { bg = 1644306, ctermbg = 233 })
vim.api.nvim_set_hl(0, "CursorLineNr", { bg = 1644306, ctermfg = 247, fg = 16777215 })
vim.api.nvim_set_hl(0, "Cyan", { ctermfg = 109, fg = 8892335 })
vim.api.nvim_set_hl(0, "Define", { fg = 6697966 })
vim.api.nvim_set_hl(0, "DiffAdd", { bg = 21795, ctermbg = 10, ctermfg = 0, fg = 15659512, link = "Dark_Green_Reverse" })
vim.api.nvim_set_hl(0, "DiffChange", { bg = 5198424, fg = 15659512, link = "Dark_Cyan_Reverse" })
vim.api.nvim_set_hl(
  0,
  "DiffDelete",
  { bold = true, cterm = { bold = true }, ctermfg = 9, fg = 16761017, link = "Red_Reverse" }
)
vim.api.nvim_set_hl(
  0,
  "DiffText",
  { bg = 29555, ctermbg = 14, ctermfg = 0, fg = 15659512, link = "Dark_Green_Reverse" }
)
vim.api.nvim_set_hl(0, "Directory", { ctermfg = 14, fg = 9238775, link = "Red" })
vim.api.nvim_set_hl(0, "EndOfBuffer", { fg = 0 })
vim.api.nvim_set_hl(0, "Error", { bg = 5832712, ctermbg = 9, ctermfg = 0, fg = 15659512, link = "Red_Reverse" })
vim.api.nvim_set_hl(0, "ErrorMsg", { ctermfg = 9, fg = 16761017, link = "Red" })
vim.api.nvim_set_hl(0, "Exception", { link = "Grey" })
vim.api.nvim_set_hl(0, "Float", { link = "Dark_Orange" })
vim.api.nvim_set_hl(0, "FoldColumn", { bg = 526344, ctermbg = 232, ctermfg = 109, fg = 8892335 })
vim.api.nvim_set_hl(0, "Folded", { bg = 0, ctermbg = 16, ctermfg = 238, fg = 4473924 })
vim.api.nvim_set_hl(0, "Function", { ctermfg = 14, fg = 9238775, link = "Dark_Red" })
vim.api.nvim_set_hl(0, "Green", { ctermfg = 101, fg = 8882015 })
vim.api.nvim_set_hl(0, "Grey", { ctermfg = 102, fg = 8882055 })
vim.api.nvim_set_hl(0, "Identifier", { ctermfg = 12, fg = 10935295, link = "Cyan" })
vim.api.nvim_set_hl(0, "IncSearch", { link = "Red_Reverse" })
vim.api.nvim_set_hl(0, "Include", { link = "Soft_Orange" })
vim.api.nvim_set_hl(0, "Keyword", { link = "Grey" })
vim.api.nvim_set_hl(0, "Label", { link = "Grey" })
vim.api.nvim_set_hl(0, "LineNr", { bg = 394758, ctermbg = 16, ctermfg = 238, fg = 4473924 })
vim.api.nvim_set_hl(0, "Macro", { link = "Soft_Orange" })
vim.api.nvim_set_hl(0, "MatchParen", { bg = 8871775, ctermbg = 95, ctermfg = 187, fg = 14671791 })
vim.api.nvim_set_hl(0, "ModeMsg", { ctermfg = 10, fg = 11794112, link = "Soft_Yellow" })
vim.api.nvim_set_hl(0, "MoreMsg", { ctermfg = 14, fg = 9238775, link = "Soft_Orange" })
vim.api.nvim_set_hl(0, "NonText", { ctermfg = 236, fg = 1122867 })
vim.api.nvim_set_hl(0, "Normal", { bg = 0, ctermbg = 232, ctermfg = 187, fg = 14671791 })
vim.api.nvim_set_hl(0, "Number", { link = "Dark_Orange" })
vim.api.nvim_set_hl(0, "Operator", { fg = 14738154, link = "Grey" })
vim.api.nvim_set_hl(0, "Orange", { ctermfg = 137, fg = 11503455 })
vim.api.nvim_set_hl(0, "Pmenu", { bg = 1184274, ctermbg = 233, ctermfg = 240, fg = 5789784 })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = 1184274, ctermbg = 233, ctermfg = 233, fg = 1184274 })
vim.api.nvim_set_hl(
  0,
  "PmenuSel",
  { bg = 14738154, blend = 0, cterm = { reverse = true, underline = true }, fg = 2895411, link = "Dark_Red_Reverse" }
)
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = 1184274, ctermbg = 233, ctermfg = 233, fg = 1184274 })
vim.api.nvim_set_hl(0, "PreCondit", { link = "Soft_Orange" })
vim.api.nvim_set_hl(0, "PreProc", { fg = 14738154, link = "Soft_Orange" })
vim.api.nvim_set_hl(0, "Question", { ctermfg = 14, fg = 9238775, link = "Dark_Red" })
vim.api.nvim_set_hl(0, "Red", { ctermfg = 131, fg = 11493215 })
vim.api.nvim_set_hl(0, "Repeat", { link = "Grey" })
vim.api.nvim_set_hl(0, "Search", { bg = 11143938, ctermbg = 11, ctermfg = 0, fg = 14671791 })
vim.api.nvim_set_hl(0, "SignColumn", { bg = 0, ctermbg = 232, ctermfg = 101, fg = 8882015 })
vim.api.nvim_set_hl(0, "Special", { ctermfg = 14, fg = 9238775, link = "Red" })
vim.api.nvim_set_hl(0, "SpecialComment", { link = "Green_Reverse" })
vim.api.nvim_set_hl(0, "SpecialKey", { ctermfg = 234, fg = 1842204 })
vim.api.nvim_set_hl(
  0,
  "SpellBad",
  { cterm = { undercurl = true }, ctermfg = 196, fg = 16711680, sp = 16753920, undercurl = true }
)
vim.api.nvim_set_hl(
  0,
  "SpellCap",
  { cterm = { undercurl = true }, ctermfg = 111, fg = 8892415, sp = 16572564, undercurl = true }
)
vim.api.nvim_set_hl(
  0,
  "SpellLocal",
  { cterm = { undercurl = true }, ctermfg = 65, fg = 6260575, sp = 11794112, undercurl = true }
)
vim.api.nvim_set_hl(
  0,
  "SpellRare",
  { cterm = { undercurl = true }, ctermfg = 166, fg = 14114560, sp = 9238775, undercurl = true }
)
vim.api.nvim_set_hl(0, "Statement", { bold = true, cterm = { bold = true }, fg = 14738154, link = "Grey" })
vim.api.nvim_set_hl(0, "StatusLine", { bg = 0, ctermbg = 16, ctermfg = 245, fg = 9079434 })
vim.api.nvim_set_hl(0, "StatusLineNC", { bg = 0, ctermbg = 16, ctermfg = 240, fg = 5789784 })
vim.api.nvim_set_hl(0, "StatusLineTerm", { bg = 0, ctermbg = 16, ctermfg = 245, fg = 9079434 })
vim.api.nvim_set_hl(0, "StatusLineTermNC", { bg = 0, ctermbg = 16, ctermfg = 240, fg = 5789784 })
vim.api.nvim_set_hl(0, "StorageClass", { link = "Dark_Red" })
vim.api.nvim_set_hl(0, "String", { bg = 1118481, ctermbg = 233, ctermfg = 222, fg = 16768903 })
vim.api.nvim_set_hl(0, "Structure", { link = "Dark_Red" })
vim.api.nvim_set_hl(0, "TabLine", { bg = 0, ctermbg = 16, ctermfg = 240, fg = 5789784 })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = 0, ctermbg = 16, ctermfg = 240, fg = 5789784 })
vim.api.nvim_set_hl(0, "TabLineSel", { bg = 0, ctermbg = 16, ctermfg = 245, fg = 9079434 })
vim.api.nvim_set_hl(0, "Title", { bold = true, cterm = { bold = true }, fg = 14738154, link = "Soft_Orange" })
vim.api.nvim_set_hl(0, "Todo", { bg = 11143938, bold = true, cterm = { bold = true }, fg = 0 })
vim.api.nvim_set_hl(0, "Type", { fg = 14738154, link = "Orange" })
vim.api.nvim_set_hl(0, "Typedef", { link = "Dark_Red" })
vim.api.nvim_set_hl(0, "Underlined", { cterm = { underline = true }, link = "Red", underline = true })
vim.api.nvim_set_hl(0, "Visual", { bg = 1727290, ctermbg = 15, ctermfg = 0, fg = 13421772 })
vim.api.nvim_set_hl(0, "VisualNOS", { cterm = { underline = true }, underline = true })
vim.api.nvim_set_hl(0, "WarningMsg", { ctermfg = 11, fg = 16572564, link = "Red" })
vim.api.nvim_set_hl(0, "WildMenu", { link = "Dark_Red_Reverse" })
vim.api.nvim_set_hl(0, "diffBDiffer", { link = "Red" })
vim.api.nvim_set_hl(0, "diffChanged", { link = "Dark_Cyan_Reverse" })
vim.api.nvim_set_hl(0, "diffCommon", { link = "Red" })
vim.api.nvim_set_hl(0, "diffDiffer", { link = "Red" })
vim.api.nvim_set_hl(0, "diffFile", { link = "Red" })
vim.api.nvim_set_hl(0, "diffIdentical", { link = "Red" })
vim.api.nvim_set_hl(0, "diffIndexLine", { link = "Dark_Orange" })
vim.api.nvim_set_hl(0, "diffIsA", { link = "Red" })
vim.api.nvim_set_hl(0, "diffNoEOL", { link = "Red" })
vim.api.nvim_set_hl(0, "diffOnly", { link = "Red" })
vim.api.nvim_set_hl(0, "diffRemoved", { link = "Red_Reverse" })
vim.api.nvim_set_hl(0, "lCursor", { bg = 14671791, fg = 0 })
